GOPATH=`cd ../../../../../ && pwd`

run:
	# GOPATH=$(GOPATH); go build; ./client -addr shark.norgerman.com -rp 8654 -lp 1080 -loglevel 4
	GOPATH=$(GOPATH); go build; ./client -addr localhost -rp 12306 -lp 1080 -loglevel 4